# Generated by Django 3.0.7 on 2020-06-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholethingAPI', '0003_auto_20200610_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
